CREATE OR REPLACE FUNCTION PAYMENT_NUMBER (V_CONTRACT_ENDDATE DATE ,V_CONTRACT_STARTDATE DATE , V_CONTRACT_PAYMENT_TYPE VARCHAR2)
RETURN NUMBER
IS 
V_MONTH NUMBER(6);

BEGIN
       V_MONTH := MONTHS_BETWEEN(V_CONTRACT_ENDDATE,V_CONTRACT_STARTDATE);
    
       IF (V_CONTRACT_PAYMENT_TYPE = 'ANNUAL')
       THEN
          V_MONTH := V_MONTH /  12;
      ELSIF  (V_CONTRACT_PAYMENT_TYPE = 'HALF_ANNUAL')
      THEN
          V_MONTH := (V_MONTH /  12) * 2;
      ELSIF  (V_CONTRACT_PAYMENT_TYPE = 'QUARTER')
      THEN
         V_MONTH := (V_MONTH /  12) * 4;
      ELSIF  (V_CONTRACT_PAYMENT_TYPE = 'MONTHLY')
      THEN
         V_MONTH :=  V_MONTH;
       
      END IF;   
       RETURN V_MONTH; 
      
END;


CREATE OR REPLACE FUNCTION INSTALLMENTS_AMOUNT (V_CONTRACT_TOTAL_FEES NUMBER , V_CONTRACT_DEPOSIT_FEES NUMBER,V_PAYMENT_INSTALLMENT_NO NUMBER)
RETURN NUMBER
IS 
V_MONEY NUMBER(8,2);

BEGIN

 V_MONEY := (V_CONTRACT_TOTAL_FEES - NVL(V_CONTRACT_DEPOSIT_FEES,0)) /V_PAYMENT_INSTALLMENT_NO;

    RETURN  V_MONEY;  
          
END;


CREATE OR REPLACE FUNCTION NEXT_INSTALLMENT_DATE(V_CONTRACT_PAYMENT_TYPE VARCHAR2, V_CONTRACT_STARTDATE DATE)
RETURN DATE
IS

V_RESULT DATE;

BEGIN

    IF (V_CONTRACT_PAYMENT_TYPE = 'ANNUAL')
    THEN
    V_RESULT := ADD_MONTHS( V_CONTRACT_STARTDATE,12);
    ELSIF (V_CONTRACT_PAYMENT_TYPE = 'HALF_ANNUAL')
    THEN
    V_RESULT := ADD_MONTHS( V_CONTRACT_STARTDATE,6);
    ELSIF (V_CONTRACT_PAYMENT_TYPE = 'QUARTER')
    THEN
    V_RESULT := ADD_MONTHS( V_CONTRACT_STARTDATE,3);
    ELSIF (V_CONTRACT_PAYMENT_TYPE = 'MONTHLY')
    THEN
    V_RESULT := ADD_MONTHS( V_CONTRACT_STARTDATE,1);
    END IF;
    RETURN V_RESULT;
END;




