CREATE TABLE CLIENTS
(CLIENT_ID NUMBER(6) NOT NULL CONSTRAINT CLIENT_PK PRIMARY KEY,
CLIENT_NAME VARCHAR2(50) NOT NULL,
CLIENT_ADDRESS VARCHAR2(100),
CLIENT_NOTES VARCHAR2(500) )


--------------------seq/trigger pair 
-- Sequence
CREATE SEQUENCE ACCOUNTANT.CLIENTS_SEQ
START WITH 1
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;
-- Trigger
CREATE OR REPLACE TRIGGER ACCOUNTANT.CLIENTS_TRG
BEFORE INSERT
ON ACCOUNTANT.CLIENTS
REFERENCING NEW AS New OLD AS Old
FOR EACH ROW
BEGIN
-- For Toad:  Highlight column CLIENT_ID
  :new.CLIENT_ID := CLIENTS_SEQ.nextval;
END CLIENTS_TRG;
/

INSERT INTO CLIENTS(CLIENT_NAME, CLIENT_ADDRESS)
VALUES
 ('CLIENT_1', 'CAIRO'),
('CLIENT_2', 'ALEX'),
('CLIENT_3', 'CAIRO'),
('CLIENT_4', 'CAIRO');

CREATE TABLE CONTRACTS
(CONTRACT_ID NUMBER(6) NOT NULL CONSTRAINT CONTRACT_PK PRIMARY KEY,
CONTRACT_STARTDATE DATE,
CONTRACT_ENDDATE DATE,
PAYMENT_INSTALLMENT_NO NUMBER(6),
CONTRACT_TOTAL_FEES NUMBER(8,2),
CONTRACT_DEPOSIT_FEES NUMBER(8,2),
CLIENT_ID NUMBER(6),
CONTRACT_PAYMENT_TYPE VARCHAR2(25),
NOTES VARCHAR2(1000),
CONSTRAINT CLIENT_CONTRACT_FK FOREIGN KEY (CLIENT_ID) REFERENCES CLIENTS (CLIENT_ID)
);

-- Sequence
CREATE SEQUENCE ACCOUNTANT.CONTRACTS_SEQ
START WITH 102
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;
-- Trigger
CREATE OR REPLACE TRIGGER ACCOUNTANT.CONTRACTS_TRG
BEFORE INSERT
ON ACCOUNTANT.CONTRACTS
REFERENCING NEW AS New OLD AS Old
FOR EACH ROW
BEGIN
-- For Toad:  Highlight column CONTRACT_ID
  :new.CONTRACT_ID := CONTRACTS_SEQ.nextval;
END CONTRACTS_TRG;
/

CREATE TABLE INSTALLMENT_PAID
(INSTALLMENT_ID NUMBER(6) NOT NULL CONSTRAINT INSTALLMENT_PK PRIMARY KEY,
CONTRACT_ID NUMBER(6) NOT NULL,
INSTALLMENT_DATE DATE,
INSTALLMENT_AMOUNT NUMBER(10,2),
PAID NUMBER(1) ,
CONSTRAINT INSTALL_CONTRACT_FK FOREIGN KEY (CONTRACT_ID) REFERENCES CONTRACTS (CONTRACT_ID));

-- Sequence
CREATE SEQUENCE ACCOUNTANT.INSTALLMENT_PAID_SEQ
START WITH 3
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;
-- Trigger
CREATE OR REPLACE TRIGGER ACCOUNTANT.INSTALLMENT_PAID_TRG
BEFORE INSERT
ON ACCOUNTANT.INSTALLMENT_PAID
REFERENCING NEW AS New OLD AS Old
FOR EACH ROW
BEGIN
-- For Toad:  Highlight column INSTALLMENT_ID
  :new.INSTALLMENT_ID := INSTALLMENT_PAID_SEQ.nextval;
END INSTALLMENT_PAID_TRG;
/
















