CREATE  OR REPLACE TRIGGER CONTRACTS_PAYMENT_NUM_TRG
FOR INSERT OR UPDATE OF CONTRACT_STARTDATE, CONTRACT_ENDDATE, CONTRACT_PAYMENT_TYPE 
ON CONTRACTS
COMPOUND TRIGGER

V_MONTH NUMBER(6);
V_CONTRACT_ID NUMBER(6);

AFTER EACH ROW IS    
BEGIN

V_CONTRACT_ID := :NEW.CONTRACT_ID;
V_MONTH  := PAYMENT_NUMBER (:NEW.CONTRACT_ENDDATE  , :NEW.CONTRACT_STARTDATE , :NEW.CONTRACT_PAYMENT_TYPE);

END AFTER EACH ROW;

AFTER STATEMENT IS    
BEGIN

UPDATE CONTRACTS 
SET PAYMENT_INSTALLMENT_NO =  V_MONTH
WHERE CONTRACT_ID = V_CONTRACT_ID;

END AFTER STATEMENT;
END;

