CREATE OR REPLACE TRIGGER CONTRACT_DEPOSIT_FEES_TRG 
FOR  UPDATE OF PAID
   ON INSTALLMENT_PAID
   
   COMPOUND TRIGGER
   V_TOTAL_PAID    NUMBER (8, 2);
   V_CONTRACT_ID   NUMBER (6);
   AFTER EACH ROW
   IS
   BEGIN
      V_CONTRACT_ID := :NEW.CONTRACT_ID;
      V_TOTAL_PAID := :NEW.INSTALLMENT_AMOUNT;
        
   END AFTER EACH ROW;

   AFTER STATEMENT
   IS
   BEGIN
      UPDATE CONTRACTS
         SET CONTRACT_DEPOSIT_FEES = NVL(CONTRACT_DEPOSIT_FEES,0) + V_TOTAL_PAID
       WHERE CONTRACT_ID = V_CONTRACT_ID;
   
  END AFTER STATEMENT;

END;
